$(document).ready(function(){var loaderDash='<div class="text-center" style="padding-top:10px;"><div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div></div>';$("#totaltest").html(loaderDash);$("#negativeTest").html(loaderDash);$("#positivetest").html(loaderDash);$("#dist-testgraph").html(loaderDash);$("#distwisebeddv").html(loaderDash);$("#distwisecarebed").html(loaderDash);districtBar();showDistrictWiseBed('Current');showDistrictWiseCareBed();showTotalTestGraph();$(document).ajaxComplete(function(event,xhr,settings){if(settings.url==='ajax/showTotalTestGraph'){showTotalPositiveTestGraph()}
if(settings.url==='ajax/showTotalPositiveTestGraph'){showTotalNegativeTestGraph()}
if(settings.url==='ajax/showTotalNegativeTestGraph'){showTestingSummaryGraph()}})});$.ajaxSetup({headers:{'X-CSRF-TOKEN':$('meta[name="csrf-token"]').attr('content')}});function showTotalTestGraph(){$.ajax({url:"ajax/showTotalTestGraph",method:'get',data:{},success:function(result){$("#totaltest").html(result)}})}
function showTotalPositiveTestGraph(){$.ajax({url:"ajax/showTotalPositiveTestGraph",method:'get',data:{},success:function(result){$("#positivetest").html(result)}})}
function showTotalNegativeTestGraph(){$.ajax({url:"ajax/showTotalNegativeTestGraph",method:'get',data:{},success:function(result){$("#negativeTest").html(result)}})}
function showTestingSummaryGraph(){$.ajax({url:"ajax/showTestingSummaryGraph",method:'get',data:{},success:function(result){$("#dist-testgraph").html(result)}})}
function showDistrictWiseBed(type){$.ajax({url:"ajax/showDistrictWiseBed",method:'get',data:{'type':type},success:function(result){$("#distwisebeddv").html(result)}})}
function showDistrictWiseCareBed(){$.ajax({url:"ajax/showDistrictWiseCareBed",method:'get',data:{},success:function(result){$("#distwisecarebed").html(result)}})}
function showTopCountries(){$('#nav-topcountry').addClass('active');$('#nav-topcountry').addClass('show');$('#nav-topstate').removeClass('active');$('#nav-topstate').removeClass('show');$('#nav-topstate').hide();$('#nav-topcountry').show();var loaderDash='<div class="text-center" style="padding-top:10px;"><div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div></div>';$("#topCountries").html(loaderDash);$.ajax({url:"ajax/showTopCountries",method:'get',success:function(result){$('#topCountries').html(result)}})}
function districtBar(){var loaderDash='<div class="text-center" style="padding-top:10px;"><div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div></div>';$("#districtGraph").html(loaderDash);$.ajax({url:"ajax/districtBar",method:'get',success:function(result){$('#districtGraph').html(result)}})}
function showTopStates(){$('#nav-topcountry').removeClass('active');$('#nav-topcountry').removeClass('show');$('#nav-topstate').addClass('active');$('#nav-topstate').addClass('show');$('#nav-topstate').show();$('#nav-topcountry').hide();var loaderDash='<div class="text-center" style="padding-top:10px;"><div class="spinner-border" role="status"><span class="sr-only">Loading...</span></div></div>';$("#topStates").html(loaderDash);$.ajax({url:"ajax/showTopStates",method:'get',success:function(result){$('#topStates').html(result)}})}